# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='content',
            field=models.CharField(default='', max_length=200),
        ),
    ]
