# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='comment created'),
            preserve_default=False,
        ),
    ]
