# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='poem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='poem.Poem'),
        ),
    ]
