# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 03:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0005_auto_20170315_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to=settings.AUTH_USER_MODEL),
        ),
    ]
