# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0006_auto_20170315_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='validator',
            field=models.CharField(default='s', max_length=1000),
            preserve_default=False,
        ),
    ]
